#!/usr/bin/env bash

set -e -o pipefail      # exit if there are any errors
export PATH=/usr/local/bin:$PATH

echo "********************* 05-install-cwagent *********************"

echo "Installing CloudWatch Agent..."
wget https://amazoncloudwatch-agent.s3.amazonaws.com/centos/amd64/latest/amazon-cloudwatch-agent.rpm
rpm -U ./amazon-cloudwatch-agent.rpm
rm -f ./amazon-cloudwatch-agent.rpm

echo "Configuring CloudWatch Agent..."
config_path='/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json'
mv -f /tmp/amazon-cloudwatch-agent.json $config_path
#aws ssm get-parameter --name "AmazonCloudWatch-linux" --query "Parameter.Value" --output text > $config_path
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:$config_path
