#!/usr/bin/env bash

set -e -o pipefail      # exit if there are any errors
export PATH=/usr/local/bin:$PATH

echo "********************* 06-install-extras *********************"

curl -sfL https://direnv.net/install.sh | bash
